#!/usr/bin/env bash -e

# set nixos config directory
NIXOS_CONFIG_DIR="$HOME/.config/nixos"

# clone into nixos config directory
git clone "https://github.com/cybardev/nix-dotfiles.git" "$NIXOS_CONFIG_DIR"

# backup current nixos config
sudo mv "/etc/nixos" "/etc/nixos.bak"

# link new config to where old config was
sudo ln -s "$NIXOS_CONFIG_DIR" "/etc/nixos"

# use autogenerated hardware config instead of cloned one
mv "$NIXOS_CONFIG_DIR/system/hardware-configuration.nix" "$NIXOS_CONFIG_DIR/system/hardware-configuration.nix.bak"
cp "/etc/nixos.bak/hardware-configuration.nix" "$NIXOS_CONFIG_DIR/system/"

# add home-manager channel
sudo -H nix-channel --add "https://github.com/nix-community/home-manager/archive/release-24.11.tar.gz" home-manager

# add linux-surface kernel if env var set
if [[ "$SURFACE_KERNEL" -eq 1 ]]; then
    sudo -H nix-channel --add "https://github.com/NixOS/nixos-hardware/archive/b12e314726a4226298fe82776b4baeaa7bcf3dcd.tar.gz" nixos-hardware
    SURFACE_CONFIG="-I nixos-config=$NIXOS_CONFIG_DIR"
fi

# add my own channel
sudo -H nix-channel --add "https://github.com/cybardev/nix-channel/archive/main.tar.gz" cypkgs

# update nix channels
sudo -H nix-channel --update

# rebuild system from config
sudo nixos-rebuild switch $SURFACE_CONFIG
