#!/usr/bin/env bash -e

# set nixos config directory
NIXOS_CONFIG_DIR="$HOME/.config/nixos"

# clone into nixos config directory
git clone "https://github.com/cybardev/nix-dotfiles.git" "$NIXOS_CONFIG_DIR"

# use autogenerated hardware config instead of cloned one
mv "$NIXOS_CONFIG_DIR/system/hardware-configuration.nix" "$NIXOS_CONFIG_DIR/system/hardware-configuration.nix.bak"
cp "/etc/nixos.bak/hardware-configuration.nix" "$NIXOS_CONFIG_DIR/system/"

# rebuild system from config
sudo -H nixos-rebuild switch --flake "$NIXOS_CONFIG_DIR#linux"
