#!/usr/bin/env sh

draw() {
  kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in
  text/* | application/json | application/javascript)
    bat --color=always --style=plain --pager=never "$file"
    exit 0
    ;;
  image/*)
    draw "$file"
    ;;
  video/*)
    ffmpegthumbnailer -i "$file" -o /tmp/thumb.png -s 512 2>/dev/null
    draw "/tmp/thumb.png"
    ;;
  application/pdf)
    pdftoppm -f 1 -l 1 -scale-to-x 512 -scale-to-y -1 -singlefile -jpeg "$file" /tmp/pdf_preview 2>/dev/null
    draw "/tmp/pdf_preview.jpg"
    ;;
esac

pistol "$file"
